import csv

from tworoom_v51_common import *


def clarity(row, grouped=False):
    if grouped:
        return "medium-high" if row["hard_enrichment"] > 1.5 else "medium"
    if row["spatial_compactness"] < 35 and row["hard_enrichment"] > 1.5:
        return "high"
    if row["hard_enrichment"] > 1.2:
        return "medium"
    return "low"


def main():
    ensure_dirs()
    vis = load_visual()
    v4_rules = top_rule_rows(vis, "q_v4_t", k=6)
    v41_rules = [r for r in top_rule_rows(vis, "q_v41_t", k=16) if int(r["unit_id"]) in [0, 3, 7, 10, 12, 13]]
    # Read groups generated by previous script if present.
    groups = []
    p = V51_OUT / "qv4_group_summary.csv"
    if p.exists():
        with p.open() as f:
            groups = list(csv.DictReader(f))
            for g in groups:
                for k in ["hard_enrichment", "mean_residual_mag", "spatial_compactness", "coverage_top10"]:
                    g[k] = float(g[k])
    rows = []
    for r in v4_rules:
        rows.append(
            {
                "method": "V4",
                "unit_type": "rule",
                "unit_id": r["unit_id"],
                "region": r["top_hard_subset"],
                "hard_enrichment": round(r["hard_enrichment"], 3),
                "residual_magnitude": round(r["mean_residual_mag"], 3),
                "compactness": round(r["spatial_compactness"], 3),
                "clarity": clarity(r),
                "comments": "soft single rule; best read with group context",
            }
        )
    for g in groups[:6]:
        rows.append(
            {
                "method": "V4",
                "unit_type": "group",
                "unit_id": g["group_id"],
                "region": g["top_hard_subset"],
                "hard_enrichment": round(g["hard_enrichment"], 3),
                "residual_magnitude": round(g["mean_residual_mag"], 3),
                "compactness": round(g["spatial_compactness"], 3),
                "clarity": clarity(g, grouped=True),
                "comments": f"co-activated rules {g['rules']}",
            }
        )
    for r in v41_rules:
        rows.append(
            {
                "method": "V4.1",
                "unit_type": "sparse_rule",
                "unit_id": r["unit_id"],
                "region": r["top_hard_subset"],
                "hard_enrichment": round(r["hard_enrichment"], 3),
                "residual_magnitude": round(r["mean_residual_mag"], 3),
                "compactness": round(r["spatial_compactness"], 3),
                "clarity": clarity(r),
                "comments": "sparse rule; easier single-rule story",
            }
        )
    text = f"""# V5.1 V4 vs V4.1 Rule Comparison

## Unified Comparison Table

{table_md(rows, ["method", "unit_type", "unit_id", "region", "hard_enrichment", "residual_magnitude", "compactness", "clarity", "comments"])}

## Interpretation

- V4 single rules tend to preserve more performant soft rule structure, but individual rules can be less sparse.
- V4 groups are the better way to explain V4 because co-activation captures the soft rule pattern.
- V4.1 sparse rules are easier to explain one by one and now have non-empty residual-direction figures.
- For reporting, use V4 groups when discussing performance-oriented rule representations and V4.1 rules when showing white-box sparse rule examples.
"""
    write_report("03_v4_vs_v41_comparison.md", text)


if __name__ == "__main__":
    main()

